# Generated by Django 6.0.5 on 2026-06-01 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('url_video', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contenido',
            },
        ),
        migrations.CreateModel(
            name='ModuloEducativo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('url_thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'modulo_educativo',
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id_leccion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('url_video', models.CharField(blank=True, max_length=500, null=True)),
                ('numero_leccion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_contenido', models.ForeignKey(blank=True, db_column='id_contenido', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contenido')),
                ('id_modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.CASCADE, to='api.moduloeducativo')),
            ],
            options={
                'db_table': 'leccion',
            },
        ),
        migrations.CreateModel(
            name='ProgresoEducativo',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('porcentaje_completado', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_modulo', models.ForeignKey(db_column='id_modulo', on_delete=django.db.models.deletion.CASCADE, to='api.moduloeducativo')),
            ],
            options={
                'db_table': 'progreso_educativo',
                'unique_together': {('id_usuario', 'id_modulo')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id_progreso_leccion', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_leccion', models.ForeignKey(db_column='id_leccion', on_delete=django.db.models.deletion.CASCADE, to='api.leccion')),
            ],
            options={
                'db_table': 'progreso_leccion',
                'unique_together': {('id_usuario', 'id_leccion')},
            },
        ),
    ]
