# Generated by Django 6.0.5 on 2026-06-01 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='EditarMeta',
            fields=[
                ('id_editar_meta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('monto_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ahorro_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fecha_objetivo', models.DateField(default=django.utils.timezone.localdate)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'editar_meta',
            },
        ),
        migrations.CreateModel(
            name='MovimientoIngresoEgreso',
            fields=[
                ('id_movimiento_dinero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('es_ingreso', models.BooleanField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movimiento_ingreso_egreso',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInversion',
            fields=[
                ('id_movimiento_dinero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('es_ingreso', models.BooleanField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movimiento_inversion',
            },
        ),
        migrations.CreateModel(
            name='MovimientoMeta',
            fields=[
                ('id_movimiento_dinero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('es_ingreso', models.BooleanField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movimiento_meta',
            },
        ),
        migrations.CreateModel(
            name='NivelRiesgo',
            fields=[
                ('id_nivel_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nivel_riesgo',
            },
        ),
        migrations.CreateModel(
            name='TipoInversion',
            fields=[
                ('id_tipo_inversion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipo_inversion',
            },
        ),
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id_finanzas', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('monto_presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('disponible', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('id_movimiento_dinero', models.ForeignKey(blank=True, db_column='id_movimiento_dinero', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movimientoingresoegreso')),
            ],
            options={
                'db_table': 'finanzas',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('monto_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_editar_meta', models.ForeignKey(db_column='id_editar_meta', on_delete=django.db.models.deletion.CASCADE, to='api.editarmeta')),
                ('id_movimiento_dinero', models.ForeignKey(blank=True, db_column='id_movimiento_dinero', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movimientometa')),
            ],
            options={
                'db_table': 'meta',
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id_tipo_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento_pago', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_movimiento_dinero', models.ForeignKey(blank=True, db_column='id_movimiento_dinero', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movimientoingresoegreso')),
            ],
            options={
                'db_table': 'tipo_ingreso',
            },
        ),
        migrations.CreateModel(
            name='TipoIngresoInversion',
            fields=[
                ('id_tipo_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento_pago', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_movimiento_dinero', models.ForeignKey(blank=True, db_column='id_movimiento_dinero', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movimientoinversion')),
            ],
            options={
                'db_table': 'tipo_ingreso_inversion',
            },
        ),
        migrations.CreateModel(
            name='TipoIngresoMeta',
            fields=[
                ('id_tipo_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_movimiento_pago', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_movimiento_dinero', models.ForeignKey(blank=True, db_column='id_movimiento_dinero', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movimientometa')),
            ],
            options={
                'db_table': 'tipo_ingreso_meta',
            },
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id_inversion', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rentabilidad', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_movimiento_dinero', models.ForeignKey(blank=True, db_column='id_movimiento_dinero', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.movimientoinversion')),
                ('id_nivel_riesgo', models.ForeignKey(db_column='id_nivel_riesgo', on_delete=django.db.models.deletion.CASCADE, to='api.nivelriesgo')),
                ('id_tipo_inversion', models.ForeignKey(db_column='id_tipo_inversion', on_delete=django.db.models.deletion.CASCADE, to='api.tipoinversion')),
            ],
            options={
                'db_table': 'inversion',
            },
        ),
    ]
