# Generated by Django 6.0.5 on 2026-06-01 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPqr',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estado_pqr',
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('tipo_actividad', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('entidad_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_actividad', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registro_actividad',
            },
        ),
        migrations.CreateModel(
            name='Pqr',
            fields=[
                ('id_pqr', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.RESTRICT, to='api.estadopqr')),
            ],
            options={
                'db_table': 'pqr',
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id_adjunto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('tamano_bytes', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_pqr', models.ForeignKey(db_column='id_pqr', on_delete=django.db.models.deletion.RESTRICT, to='api.pqr')),
            ],
            options={
                'db_table': 'adjunto',
            },
        ),
    ]
